terraform {
  required_providers {
    libvirt = {
      source = "dmacvicar/libvirt"
    }
  }
}

provider "libvirt" {
  uri = "qemu:///system"
}

# ==============================================================================
# example6-vms — resource limits — TWO PATHS demonstrated
#
# Path A (KVM-API XML inject, terraform-driven, persistent at boot)
#   vm_loose     → no limits (baseline for comparison)
#   vm_throttled → cpu/io/network in vm_profile + enable_config = true
#                  Values baked into libvirt domain XML on creation.
#                  Inspect immediately after apply via virsh + dumpxml.
#                  Burst values: some attributes may be rejected by the
#                  provider's iotune schema — for burst use Path B.
#
# Path B (sidecar live-apply via quick-throttle* triplet)
#   vms_workers  → 3-VM set, NO limits in vm_profile.
#                  Throttle profiles + mapping + apply/clear scripts
#                  generated by quick-throttle / quick-throttle-apply /
#                  quick-throttle-runner.
#                  Workflow: edit .qv-limits/ex6-throttle.ini → run apply.sh.
#
# Inspect after `terraform apply`
#   # Path A (visible immediately after apply):
#   virsh dumpxml qvms-ex6-throttled | grep -E "cputune|iotune|bandwidth"
#   virsh schedinfo qvms-ex6-throttled
#   virsh blkdeviotune qvms-ex6-throttled vda
#
#   # Path B (requires manual assignment + apply.sh):
#   ls .qv-limits/                                         # see generated files
#   $EDITOR .qv-limits/ex6-throttle.ini                    # assign profiles per VM
#   bash .qv-limits/qv-throttle.apply.sh .qv-limits/ex6-throttle.ini
#   bash .qv-limits/qv-throttle.clear.sh .qv-limits/ex6-throttle.ini
# ==============================================================================

locals {
  prefix = "qvms-ex6"

  kvm_networks = {
    "qvexample-neta-loc-1" = { enabled = true }
    "qvexample-neta-loc-2" = { enabled = true }
    "qvexample-net-bridge" = { enabled = false }
  }

  ssh = {
    user          = "ubuntu"
    identity_file = "~/.ssh/id_rsa"
    public_key    = file("~/.ssh/id_rsa.pub")
  }

  user_data = templatefile("${path.module}/templates/user-data.tmpl", {
    user_name     = local.ssh.user
    user_password = "ubuntu123"
    ssh_pub_key   = local.ssh.public_key
  })

  base_profile = {
    vcpu   = 2
    memory = 2048
  }
}

# ------------------------------------------------------------------------------
# Path A.1 — vm_loose: baseline VM, no throttle.
# ------------------------------------------------------------------------------
module "vm_loose" {
  source       = "../../modules/quick-vm"
  name         = "${local.prefix}-loose"
  os_name      = "ubuntu_22"
  user_data    = local.user_data
  vm_profile   = local.base_profile
  kvm-networks = local.kvm_networks
  networks = [
    { profile_name = "qvexample-neta-loc-1", ip = "192.168.200.90" },
    { profile_name = "qvexample-neta-loc-2", ip = "192.168.201.90" },
    { profile_name = "qvexample-net-bridge", ip = "172.16.0.90" }
  ]
}

# ------------------------------------------------------------------------------
# Path A.2 — vm_throttled: KVM-API XML inject (enable_config = true).
# CPU + I/O + network bandwidth persist in libvirt domain XML.
# Visible immediately after `terraform apply` via virsh — no extra step.
# ------------------------------------------------------------------------------
module "vm_throttled" {
  source       = "../../modules/quick-vm"
  name         = "${local.prefix}-throttled"
  os_name      = "ubuntu_22"
  user_data    = local.user_data
  kvm-networks = local.kvm_networks

  vm_profile = merge(local.base_profile, {
    cpu = {
      limit = {
        percent = 25 # 25% of total allocated CPU capacity (~0.5 of 2 vCPU)
      }
    }

    io = {
      vda = {
        bytes_unit      = "MB"
        read_bytes_sec  = 10
        write_bytes_sec = 5
        read_iops_sec   = 1000
        write_iops_sec  = 500
      }
    }

    network = {
      "0" = {
        rate_unit = "MB"
        inbound = {
          average = 10
          peak    = 50
          burst   = 1
        }
        outbound = {
          average = 5
          peak    = 20
          burst   = 1
        }
      }
    }

    enable_config = true # XML inject path
  })

  networks = [
    { profile_name = "qvexample-neta-loc-1", ip = "192.168.200.91" },
    { profile_name = "qvexample-neta-loc-2", ip = "192.168.201.91" },
    { profile_name = "qvexample-net-bridge", ip = "172.16.0.91" }
  ]
}

# ------------------------------------------------------------------------------
# Path B — vms_workers: 3-VM set. vm_profile has ONLY {vcpu, memory}; throttle
# is configured via the 3 quick-throttle modules below. After apply, edit
# .qv-limits/ex6-throttle.ini to assign profiles to specific workers.
# ------------------------------------------------------------------------------
module "vms_workers" {
  source       = "../../modules/quick-vms"
  kvm-networks = local.kvm_networks

  machines = {
    workers = {
      set_name   = "${local.prefix}-worker"
      os_name    = "ubuntu_22"
      vm_profile = local.base_profile

      user_data = local.user_data

      nodes = [
        { name = "v1", networks = [
          { profile_name = "qvexample-neta-loc-1", ip = "192.168.200.92" },
          { profile_name = "qvexample-neta-loc-2", ip = "192.168.201.92" },
          { profile_name = "qvexample-net-bridge", ip = "172.16.0.92" },
        ] },
        { name = "v2", networks = [
          { profile_name = "qvexample-neta-loc-1", ip = "192.168.200.93" },
          { profile_name = "qvexample-neta-loc-2", ip = "192.168.201.93" },
          { profile_name = "qvexample-net-bridge", ip = "172.16.0.93" },
        ] },
        { name = "v3", networks = [
          { profile_name = "qvexample-neta-loc-1", ip = "192.168.200.94" },
          { profile_name = "qvexample-neta-loc-2", ip = "192.168.201.94" },
          { profile_name = "qvexample-net-bridge", ip = "172.16.0.94" },
        ] },
      ]
    }
  }
}

# ------------------------------------------------------------------------------
# Path B throttle triplet for the workers set.
# ------------------------------------------------------------------------------
module "throttle" {
  source     = "../../modules/quick-throttle"
  output_dir = path.root
  prefix     = "ex6"

  cpu_configs = {
    cap25 = { limit = { percent = 25 } }
    cap50 = { limit = { percent = 50 } }
  }

  disk_configs = {
    workers_io = {
      vda = {
        bytes_unit      = "MB"
        read_bytes_sec  = 20
        write_bytes_sec = 10
        read_iops_sec   = 2000
        write_iops_sec  = 1000

        # Burst — only usable via Path B (live virsh schedinfo/blkdeviotune).
        write_bytes_sec_max        = 20
        write_bytes_sec_max_length = 10
      }
    }
  }

  network_configs = {
    slow = {
      "0" = {
        rate_unit = "MB"
        inbound   = { average = 10 }
        outbound  = { average = 5 }
      }
    }
  }
}

module "throttle_apply" {
  source             = "../../modules/quick-throttle-apply"
  output_dir         = path.root
  prefix             = "ex6"
  vms                = module.vms_workers.vms_info_by_set["workers"]
  available_profiles = module.throttle.available_files
}

module "throttle_runner" {
  source     = "../../modules/quick-throttle-runner"
  output_dir = path.root
}

# ------------------------------------------------------------------------------
# Outputs
# ------------------------------------------------------------------------------
output "vms" {
  value = {
    loose = {
      name     = module.vm_loose.vm_name
      networks = module.vm_loose.vm_networks
      note     = "No limits - baseline reference"
    }
    throttled = {
      name     = module.vm_throttled.vm_name
      networks = module.vm_throttled.vm_networks
      note     = "Path A: enable_config XML inject (cpu/io/network in domain XML)"
      verify_cmd = "virsh dumpxml ${module.vm_throttled.vm_name} | grep -E 'cputune|iotune|<bandwidth'"
    }
  }
}

output "workers" {
  value = module.vms_workers.vms_info
}

output "throttle" {
  value = {
    note               = "Path B: edit .qv-limits/ex6-throttle.ini then run apply.sh"
    mapping_file       = module.throttle_apply.mapping_file
    apply_script       = module.throttle_runner.apply_script
    clear_script       = module.throttle_runner.clear_script
    available_profiles = module.throttle.available_files
  }
}
