# ============================================================================
# Inputs for quick-throttle-apply
# ============================================================================

variable "output_dir" {
  type        = string
  description = "Directory under which .qv-limits/ is created. Typically path.root. Output file: <output_dir>/.qv-limits/<prefix>-throttle.ini (alongside per-axis files generated by quick-throttle)."
}

variable "prefix" {
  type        = string
  description = "Mandatory namespace prefix. Mapping file is named <prefix>-throttle.ini. Match this with quick-throttle's prefix so the profile filenames referenced match what's on disk."
  validation {
    condition     = length(var.prefix) > 0 && can(regex("^[A-Za-z0-9][A-Za-z0-9_-]*$", var.prefix))
    error_message = "prefix must be non-empty and contain only alphanumerics, underscore, hyphen (starting with alphanumeric)."
  }
}

variable "available_profiles" {
  type = object({
    cpu     = list(string)
    disk    = list(string)
    network = list(string)
  })
  description = "Optional per-axis list of available profile filenames (basenames, e.g. 'k3s2-lap-cpu-cap25.ini'). When provided, mapping file gets a header comment listing all options — handy when manually editing throttle.ini. Pass module.quick_throttle.available_files."
  default     = { cpu = [], disk = [], network = [] }
}


variable "vms" {
  type        = any
  description = <<-EOT
    List of VM spec objects. Each entry must have at minimum:
      - name             (string)               — section header in throttle.ini
      - networks         (list with .index)     — produces network_profile.<idx> lines
      - disks            (list of strings)      — produces disk_profile.<dev> lines

    quick-vm.vm_info satisfies this exactly. Pass via:
      vms = [module.master_m1.vm_info, module.master_m2.vm_info, ...]

    Extra fields are tolerated and ignored.
  EOT
}